import {
    isIncludeDirective,
    UseDirective,
    Token,
    IncludeDirective,
    ParseResult,
    StatementDirective,
    Compiler,
    CompilerProgramOptions,
    CompilerOutput,
    CompilerProgram,
    RecompileOutput
} from './types.js';
import { dirname, join } from 'path';
import { DiagnosticCategory, DiagnosticMessage } from './diagnostic-message.js';
import { tokenize } from './tokenizer.js';
import { parse } from './parser.js';
import { sys } from './sys.js';
import {
    findProjectConfig,
    readProjectConfig,
    resolveProjectFiles,
    SasqlConfig
} from './config.js';
import { TokenPosnMap } from './lookup.js';

export function createCompilerProgram(
    projectRootDir: string,
    options?: CompilerProgramOptions
): CompilerProgram {
    /** Holds the source files for entry file and all descendents. */
    const compilers = new Map<string, Compiler>();

    class _Compiler implements Compiler {
        public imports: Record<string, Compiler> = {};

        public dependants: Record<string, Compiler> = {};

        public statements: Record<string, StatementDirective> = {};

        public output: string | undefined;

        public formatted: string | undefined;

        public diagnosticMessages: DiagnosticMessage[] = [];

        public unknownExceptions: unknown[] = [];

        public initialized = false;

        public positions: TokenPosnMap = new TokenPosnMap();

        constructor(
            public srcPath: string,
            public source: string,
            public srcToken?: UseDirective
        ) {}

        recompile(source?: string): RecompileOutput {
            // Clear diagnostic messages
            this.diagnosticMessages.length = 0;
            this.unknownExceptions.length = 0;

            source ??= sys.readFile(this.srcPath);
            if (!source) {
                throw new Error('Source no longer exists');
            }
            this.source = source;

            const results = this.compile();

            const recompiled: {
                [fsPath: string]: CompilerOutput;
            } = {};

            // Recompile all files that import this file
            Object.values(this.dependants).forEach((compiler) => {
                const output = compiler.recompile();
                recompiled[compiler.srcPath] = output;
            });

            return {
                diagnosticMessages: this.diagnosticMessages,
                unknownExceptions: this.unknownExceptions,
                output: results.output,
                recompiled,
                positions: results.positions
            };
        }

        compile(): CompilerOutput {
            this.initialized = true;

            // Tokenize the source text
            const tokens = this._tokenize();

            // Parse the source tokens
            const { imports, chunks, statements, positions } =
                this._parseSrc(tokens);

            this.positions = positions;
            this.statements = statements;

            // Resolve and compile imports
            Object.entries(imports).forEach(([alias, use]) => {
                try {
                    this._resolveImport(alias, use);
                } catch (e) {
                    this._onError(e);
                }
            });

            // Compile anything that is not an import or a directive
            this.output = chunks
                .map((chunk) => {
                    if (!isIncludeDirective(chunk)) return chunk.text;

                    try {
                        return this._resolveInclude(chunk);
                    } catch (e) {
                        this._onError(e);
                        return '';
                    }
                })
                .join(' ');

            return {
                output: this.output,
                positions,
                diagnosticMessages: this.diagnosticMessages,
                unknownExceptions: this.unknownExceptions
            };
        }

        /**
         * Tokenizes a source .sasql string.
         * @returns An array of {@link Token}
         */
        private _tokenize() {
            let tokens: Token[] = [];

            if (this.source) {
                try {
                    const tokenizeResult = tokenize(this.source, this.srcPath, {
                        ignoreWhitespace: options?.ignoreWhitespace || true
                    });

                    tokens = tokenizeResult.tokens;
                    this.diagnosticMessages.push(
                        ...tokenizeResult.diagnosticMessages
                    );
                } catch (e) {
                    this._onError(e);
                }
            }

            return tokens;
        }

        /**
         * Parses the tokens generated by the `_tokenize` method.
         * @param tokens An array of tokens
         * @returns The output of the {@link parse} function
         */
        private _parseSrc(tokens: Token[]): ParseResult {
            try {
                const parseResult = parse(tokens, this.source, this.srcPath, {
                    removeComments: options?.removeComments ?? true
                });

                this.diagnosticMessages.push(...parseResult.diagnosticMessages);
                this.unknownExceptions.push(...parseResult.unknownExceptions);

                return parseResult;
            } catch (e) {
                this._onError(e);
            }

            return {
                imports: {},
                chunks: [],
                statements: {},
                diagnosticMessages: this.diagnosticMessages,
                unknownExceptions: this.unknownExceptions,
                positions: new TokenPosnMap()
            };
        }

        //
        // Import Logic
        //

        /**
         * Resolves files imported with `@use`
         * @param alias An import alias
         * @param use A `@use` directive
         * @todo identify circular dependencies
         */
        private _resolveImport(alias: string, use: UseDirective): void {
            let absolutePath: string;

            try {
                absolutePath = this._resolveImportPath(use.path, use.path.text);
            } catch (e) {
                this._onError(e);
                return;
            }

            // Safeguard - this import might already have been initialized
            if (this.imports[absolutePath]) {
                this.diagnosticMessages.push(
                    ...this.imports[absolutePath].diagnosticMessages
                );
                this.unknownExceptions.push(
                    ...this.imports[absolutePath].unknownExceptions
                );
                return;
            }

            // A compiler has already been created for this import
            if (compilers.has(absolutePath)) {
                const imported = compilers.get(absolutePath)!;

                this.imports[alias] = imported;
                imported.dependants[this.srcPath] = <Compiler>this;

                // A compiler exists, but this import hasn't yet been compiled
                if (imported.initialized === false) {
                    imported.compile();
                }

                // Attach the imported file's diagnostic messages
                this.diagnosticMessages.push(...imported.diagnosticMessages);
                this.unknownExceptions.push(...imported.unknownExceptions);

                return;
            }

            // This import is not included via the program config,
            // but it is included by virtue of it being imported

            // Path already confirm existing by `_resolveImportPath`
            const importedSrc = sys.readFile(absolutePath);
            if (importedSrc === undefined) {
                throw new DiagnosticMessage(
                    'Unable to load import.',
                    DiagnosticCategory.ERROR,
                    this.source,
                    this.srcPath,
                    use.path
                );
            }

            // Create a compiler for the imported file
            const compiler = new _Compiler(absolutePath, importedSrc, use);

            // Register `this` as a dependant of the import
            compiler.dependants[this.srcPath] = this;

            // Associate the import with its alias
            this.imports[alias] = compiler;

            // Compile the imported file
            const output = compiler.compile();

            // Attach the imported file's diagnostic messages
            this.diagnosticMessages.push(...output.diagnosticMessages);
            this.unknownExceptions.push(...output.unknownExceptions);

            // Register the compiler with this module
            compilers.set(absolutePath, compiler);
        }

        /**
         * Resolves the path of a file imported with `@use`.
         * @param lastToken The last loaded token, used for error positioning
         * @param path An absolute path or a path relative to this file
         * @returns An absolute path to the file at `path`
         * @throws Will throw a {@link DiagnosticMessage} if the file cannot be resolved
         */
        private _resolveImportPath(lastToken: Token, path: string) {
            // Remove any trailing or leading quotes
            if (/^["']/.test(path)) path = path.substring(1);
            if (/["']$/.test(path)) path = path.substring(0, path.length - 1);

            // Append file extension if it wasn't included in the import path
            if (!path.endsWith('.sasql')) path += '.sasql';

            // If the file does nto exist, we might need to resolve it
            if (!sys.fileExists(path)) {
                const srcDir = dirname(this.srcPath);
                path = join(srcDir, path);

                if (!sys.fileExists(path)) {
                    throw new DiagnosticMessage(
                        'Failed to resolve import at path.',
                        DiagnosticCategory.ERROR,
                        this.source,
                        this.srcPath,
                        lastToken
                    );
                }
            }

            return path;
        }

        //
        // Include Logic
        //

        /**
         * Resolves an `@include` directive, returning the referenced
         * statement's content.
         * @param include A `@include` directive
         * @returns The content of the imported directive
         */
        private _resolveInclude(include: IncludeDirective): string {
            const { import: imported, module } = include;

            let resolvedStatement: StatementDirective;

            if (!module) {
                resolvedStatement = this.statements[imported.text];
            } else {
                const resolvedImport = this.imports[module.text];
                if (!resolvedImport) {
                    throw new DiagnosticMessage(
                        `Failed to resolve module ${module.text}.`,
                        DiagnosticCategory.ERROR,
                        this.source ?? '',
                        this.srcPath,
                        module
                    );
                }

                resolvedStatement = resolvedImport.statements[imported.text];
            }

            if (!resolvedStatement) {
                throw new DiagnosticMessage(
                    'Failed to resolve @include',
                    DiagnosticCategory.ERROR,
                    this.source,
                    this.srcPath,
                    imported
                );
            }

            // @to-do - add validation here
            return resolvedStatement.bracedExpression
                .map((token) => token.text)
                .join(' ');
        }

        //
        // Helper Function
        //

        private _onError(e: unknown) {
            if (e instanceof DiagnosticMessage) {
                this.diagnosticMessages.push(e);
            } else {
                this.unknownExceptions.push(e);
            }
        }
    }

    let projectConfig: SasqlConfig;

    if (options?.programConfig) {
        projectConfig = options.programConfig;
    } else {
        const projectConfigPath = findProjectConfig(projectRootDir);
        projectConfig = readProjectConfig(projectConfigPath);
    }

    const projectFiles = resolveProjectFiles(projectRootDir, projectConfig);

    projectFiles.projectFiles.forEach(({ source, fsPath }) => {
        if (!source) return;
        const compiler = new _Compiler(fsPath, source);
        compilers.set(fsPath, compiler);
    });

    function compileProject() {
        let output: Record<string, string> = {};
        const diagnosticMessages: DiagnosticMessage[] = [];
        const unknownExceptions: unknown[] = [];

        Array.from(compilers.keys()).forEach((k) => {
            const result = compilers.get(k)!.compile();

            diagnosticMessages.push(...result.diagnosticMessages);
            unknownExceptions.push(...result.unknownExceptions);

            output[k] = result.output;
        });

        return {
            output,
            diagnosticMessages,
            unknownExceptions
        };
    }

    return { compilers, compileProject };
}
